@database = BigBoxStore
@collection = GroceryInventory
@domain = http://localhost
@port = 3000
###
GET {{domain}}:{{port}}/find/{{database}}/{{collection}}
Content-Type: application/json

###
POST {{domain}}:{{port}}/insert/{{database}}/{{collection}}
Content-Type: application/json

{
  "document": {
    "item": "butter",
    "food_group": "dairy",
    "price_in_usd": 4,
    "quantity": 150,
    "calories_per_100g": 120
  }
}

###
@id = 6723eff8516023421a145700
DELETE {{domain}}:{{port}}/delete/{{database}}/{{collection}}/{{id}}
Content-Type: application/json